Merge from dependabot/dependabot-core (#43)
* Update to poetry to 1.0.10

Reformat regexes for readability.

* Bump jest from 26.4.0 to 26.4.2 in /npm_and_yarn/helpers

Bumps [jest](https://github.com/facebook/jest) from 26.4.0 to 26.4.2.
- [Release notes](https://github.com/facebook/jest/releases)
- [Changelog](https://github.com/facebook/jest/blob/master/CHANGELOG.md)
- [Commits](https://github.com/facebook/jest/compare/v26.4.0...v26.4.2)

Signed-off-by: dependabot[bot] <support@github.com>

* Bump phpstan/phpstan from 0.12.37 to 0.12.39 in /composer/helpers

Bumps [phpstan/phpstan](https://github.com/phpstan/phpstan) from 0.12.37 to 0.12.39.
- [Release notes](https://github.com/phpstan/phpstan/releases)
- [Commits](https://github.com/phpstan/phpstan/compare/0.12.37...0.12.39)

Signed-off-by: dependabot[bot] <support@github.com>

* Hacky bundle cache implementation

* Run bundle cache in file updater

* Change dry-run for vendoring

* Add cloned repo to updater checker and file updater

* Work on temp git repo

* dry-run: list added/deleted files

* bundler: cache_all_platforms

This is required for vendoring gems with native dependencies.

* Only prune unlocked gems

* Add content_encoding

* Add target_directory

* Add test for file updater vendoring

* Add test for custom vendor pruning

* Move git config to CI container

* Remove puts debug lines

* Only replace version part of cargo line

We do a rather straight-forward regex replace on Cargo versions,
however, we did not take into account that the dependency name can
include the the version string. In order to avoid this, we only change
the part of the string after the `=` mark.

* Add --no-tag and --np-recurse-submodules options to git clone

* Ensure files written to cache dir are deleted

* bundler vendoring: git sources

* Load gemfile and lockfile from project fixtures

* Improve wording in build_tmp_repo helper

* Add DependencyFile#decoded_content

This helps DRY up dealing with encoded content from a DependencyFile.

* Add comment to address existing git repo flow

The repo that already exists might be on a different branch or in some
other weird state, and we do nothing to prevent this from happening.

In production and on CI this runs in an ephemeral environment so we
don't expect to run into this.

* v0.119.0

* lint: line len

* lint: ignore fixtures

don't push your politics on me pal

* Load gemfile and lockfile from project fixtures part2

* bundler vendoring: detect non-binary extensions

* Bump phpstan/phpstan from 0.12.39 to 0.12.40 in /composer/helpers

Bumps [phpstan/phpstan](https://github.com/phpstan/phpstan) from 0.12.39 to 0.12.40.
- [Release notes](https://github.com/phpstan/phpstan/releases)
- [Commits](https://github.com/phpstan/phpstan/compare/0.12.39...0.12.40)

Signed-off-by: dependabot[bot] <support@github.com>

* my magic > MimeMagic

* Dockerfile.dev: set git author

* v0.119.1

* Don't downgrade a pinned commit to a tag.

* Support cargo 1.46.0 ref not found message

In cargo 1.45.0 the message we were matching against was:

```
    Updating crates.io index
    Updating git repository `https://github.com/BurntSushi/utf8-ranges`
error: failed to get `utf8-ranges` as a dependency of package `dependabot v0.1.0 (/home/dependabot/dependabot-core/cargo/tmp/dependabot_20200902-3407-1pi6vdm)`

Caused by:
  failed to load source for dependency `utf8-ranges`

Caused by:
  Unable to update https://github.com/BurntSushi/utf8-ranges#11111b37

Caused by:
  revspec '11111b376b93484341c68fbca3ca110ae5cd2708' not found; class=Reference (4); code=NotFound (-3)
```

In cargo 1.46.0 this has been changed to:

```
    Updating crates.io index
    Updating git repository `https://github.com/BurntSushi/utf8-ranges`
error: failed to get `utf8-ranges` as a dependency of package `dependabot v0.1.0 (/home/dependabot/dependabot-core/cargo/tmp/dependabot_20200902-15-ij9hoa)`

Caused by:
  failed to load source for dependency `utf8-ranges`

Caused by:
  Unable to update https://github.com/BurntSushi/utf8-ranges#11111b37

Caused by:
  object not found - no match for id (11111b376b93484341c68fbca3ca110ae5cd2708); class=Odb (9); code=NotFound (-3)
```

This change matches against both messages, and ensures we raise a
`GitDependencyReferenceNotFound` as expected.

* Bump prettier from 2.0.5 to 2.1.1 in /npm_and_yarn/helpers

Bumps [prettier](https://github.com/prettier/prettier) from 2.0.5 to 2.1.1.
- [Release notes](https://github.com/prettier/prettier/releases)
- [Changelog](https://github.com/prettier/prettier/blob/master/CHANGELOG.md)
- [Commits](https://github.com/prettier/prettier/compare/2.0.5...2.1.1)

Signed-off-by: dependabot[bot] <support@github.com>

* Don't fail-fast in matrix

We do not want other jobs to get cancelled when one of them fails.

* v0.119.2

* Bump phpstan/phpstan from 0.12.40 to 0.12.42 in /composer/helpers

Bumps [phpstan/phpstan](https://github.com/phpstan/phpstan) from 0.12.40 to 0.12.42.
- [Release notes](https://github.com/phpstan/phpstan/releases)
- [Commits](https://github.com/phpstan/phpstan/compare/0.12.40...0.12.42)

Signed-off-by: dependabot[bot] <support@github.com>

* Bump eslint from 7.7.0 to 7.8.1 in /npm_and_yarn/helpers

Bumps [eslint](https://github.com/eslint/eslint) from 7.7.0 to 7.8.1.
- [Release notes](https://github.com/eslint/eslint/releases)
- [Changelog](https://github.com/eslint/eslint/blob/master/CHANGELOG.md)
- [Commits](https://github.com/eslint/eslint/compare/v7.7.0...v7.8.1)

Signed-off-by: dependabot[bot] <support@github.com>

* Upgrade elixir/mix to 1.10.0

Co-authored-by: Tom Rochette <roctom@gmail.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Jurre Stender <jurre@github.com>
Co-authored-by: Philip Harrison <philip@mailharrison.com>
Co-authored-by: Peter Wagner <git@mycloudand.me>
Co-authored-by: Pete Wagner <thepwagner@github.com>
Co-authored-by: Markus Reiter <me@reitermark.us>